security:
  oauth2:
#    客户端配置
    client:
#      客户端用户名密码
      client-id: client1
      client-secret: client1secret
#      用户认证url
      user-authorization-uri: http://localhost:8080/server/oauth/authorize
#      token验证url
      access-token-uri: http://localhost:8080/server/oauth/token
    resource:
      jwt:
#        jwt密钥url
        key-uri: http://localhost:8080/server/oauth/token_key
server:
  port: 8081
  servlet:
    context-path: /client1
